name: Matrix Workflow
on:
    push
jobs:
    deploy:
        strategy: 
            matrix:
                os: [ubuntu-latest, ubuntu-20.04]
                image: [hello-world, alpine]
        runs-on: ${{matrix.os}}
        steps:
            - name: deploy image on ${{matrix.os}}
              run: docker run ${{matrix.image}}